import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <body className='scrollbar-thin scrollbar-thumb-gray-900 scrollbar-track-gray-100'>{children}</body>
      </html>
  )
}
